# Generated by Django 3.1.3 on 2024-05-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
                ('releaseYear', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('imageUrl', models.URLField()),
            ],
        ),
    ]
